### ISSUE TITLE
ConcurrentModificationException in log when looking at tooltips

### ISSUE THREAD

**Issue by The-Fireplace** [TheCBProject/NotEnoughItems#102]
```
[21:47:18] [NEI Item Filtering/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@2e27c824:
java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207) ~[?:1.8.0_25]
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1261) ~[?:1.8.0_25]
	at codechicken.nei.LayoutManager.handleTooltip(LayoutManager.java:245) ~[LayoutManager.class:?]
	at codechicken.nei.handler.NEIClientEventHandler.itemTooltipEvent(NEIClientEventHandler.java:336) ~[NEIClientEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_382_NEIClientEventHandler_itemTooltipEvent_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:277) [ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:785) [afj.class:?]
	at codechicken.nei.util.helper.GuiHelper.itemDisplayNameMultiline(GuiHelper.java:180) [GuiHelper.class:?]
	at codechicken.nei.util.helper.GuiHelper.concatenatedDisplayName(GuiHelper.java:228) [GuiHelper.class:?]
	at codechicken.nei.util.ItemInfo.getSearchName(ItemInfo.java:51) [ItemInfo.class:?]
	at codechicken.nei.util.ItemList$PatternItemFilter.matches(ItemList.java:84) [ItemList$PatternItemFilter.class:?]
	at codechicken.nei.util.ItemList$AnyMultiItemFilter.matches(ItemList.java:132) [ItemList$AnyMultiItemFilter.class:?]
	at codechicken.nei.util.ItemList$AllMultiItemFilter.matches(ItemList.java:104) [ItemList$AllMultiItemFilter.class:?]
	at codechicken.nei.util.ItemList$2.execute(ItemList.java:267) [ItemList$2.class:?]
	at codechicken.lib.thread.RestartableTask$1.run(RestartableTask.java:32) [RestartableTask$1.class:?]
```

Loaded mods:
http://modlister.com/user/The_Fireplace

NEI Version:
1.11.2-2.2.0.216

**Comment by covers1624** [comment]
Duplicate, fixed in dev.
