### ISSUE TITLE
[1.10.2] Tessellating CCL block in world with Thermal Dynamics

### ISSUE THREAD

**Issue by JonasCiss** [TheCBProject/NotEnoughItems#120]
I got this error several times and the game crashed.

java.lang.NullPointerException: Tessellating CCL block in world
at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:124)
at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:186)
at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockQuads(CoverRenderer.java:69)
at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockCover(CoverRenderer.java:140)
at cofh.thermaldynamics.duct.attachments.cover.Cover.render(Cover.java:119)
at cofh.thermaldynamics.render.RenderDuct.renderBlock(RenderDuct.java:387)
at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:94)
at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:53)
at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:95)
at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:293)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
at java.lang.Thread.run(Unknown Source)

**Comment by covers1624** [comment]
Full log, and this is not the place for this issue but whatever. Full log, no smug reports.

**Comment by JonasCiss** [comment]
Sorry, I came to the false page. But here is the file.
[crash-2017-08-22_09.13.04-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/1241915/crash-2017-08-22_09.13.04-client.txt)

**Comment by covers1624** [comment]
What type of cover did you place on the duct? anything from chisel?

**Comment by JonasCiss** [comment]
Chisel is not present. There are dirt covers and covers made from black granite cobblestone of Underground Biomes Contructs.

**Comment by covers1624** [comment]
Ok, CoFH issue reopened, its valid.
