### ISSUE TITLE
NEI 1.12.1 - NPE @ RenderItemFrame:35

### ISSUE THREAD

**Issue by mcsnetworks** [TheCBProject/NotEnoughItems#126]
Hello,
Version: NotEnoughItems-1.12-2.4.0.231-universal
Forge: 1.12.1-14.22.1.2481

Issue: Crash to desktop on launch.

Debug:
java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.entity.RenderItemFrame.<init>(RenderItemFrame.java:35)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:206)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:517)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:137)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by covers1624** [comment]
1, Please don't provide a smug report.
2, NEI is not in that stacktrace.

**Comment by mcsnetworks** [comment]
Please disregard.  Turned out to be an issue with a incorrectly configured ASM Mixin.
