### ISSUE TITLE
this mod Not 1.9 or 1.8.8 or 1.8.8 versions？

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [TheCBProject/NotEnoughItems#14]
Why not 1.9 or 1.8.8 or 1.8.9 versions？@Chicken-Bones @covers1624 
（Not like FEI and JEI.）

**Comment by Dragonisser** [comment]
http://chickenbones.net/Pages/links.html

There is a 1.9 and 1.8 version...

**Comment by mgdgfbhevdyeh** [comment]
@Dragonisser but's 1.8.8 or 1.8.9?

**Comment by Dragonisser** [comment]
Just use the 1.8 version it should work with all 1.8 versions, same for 1.9

**Comment by mgdgfbhevdyeh** [comment]
1.8 NEI and chincken bone in 1.8.9 forge 1764... ...（minecraft crash）


[19:27:01] [AWT-EventQueue-0/INFO] Start generating launching command...
[19:27:01] [Game Launcher/INFO] Logging in...
[19:27:01] [Game Launcher/INFO] Detecting libraries...
[19:27:01] [Game Launcher/INFO] Unpacking natives...
[19:27:08] [Game Launcher/INFO] *** Make shell command ***
[19:27:08] [Game Launcher/INFO] On making head command.
[19:27:08] [Game Launcher/INFO] Java Version: 1.8.0_91
[19:27:08] [Game Launcher/INFO] Java Platform: 32
[19:27:08] [Game Launcher/INFO] System Platform: 32
[19:27:08] [Game Launcher/INFO] System Physical Memory: 3544
[19:27:08] [Game Launcher/INFO] On making launcher args.
[19:27:08] [Game Launcher/INFO] Starting process
[19:27:08] [Game Launcher/INFO] The game process have been started
 18, 2016 7:27:08  org.jackhuang.hellominecraft.launcher.Launcher main

 *** Hello Minecraft! Launcher 2.4.0.28 ***

 18, 2016 7:27:08 org.jackhuang.hellominecraft.launcher.Launcher main

*** Launching Game ***

2016-08-18 19:27:09,164 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

2016-08-18 19:27:09,165 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

[19:27:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

[19:27:09] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

[19:27:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker

[19:27:09] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.1764 for Minecraft 1.8.9 loading

[19:27:09] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_91, running on Windows 7:x86:6.1, installed at C:\Program Files\Java\jre1.8.0_91

2016-08-18 19:27:09,309 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

2016-08-18 19:27:09,322 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

2016-08-18 19:27:09,324 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

[19:27:09] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: java.lang.RuntimeException: java.lang.NoSuchFieldException: loadedCoremods

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:552)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at codechicken.core.launch.DepLoader$DepLoadInst.activateDeps(DepLoader.java:502)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:496)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at codechicken.core.launch.DepLoader.load(DepLoader.java:684)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.reflect.Constructor.newInstance(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.Class.newInstance(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.reflect.Method.invoke(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:127)

[19:27:09] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchFieldException: loadedCoremods

[19:27:09] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.Class.getDeclaredField(Unknown Source)

[19:27:09] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:539)

[19:27:09] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     ... 23 more

[19:27:09] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at F:\Minecraft 1.8.9\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.1764 for Forge Mod Loader

java.lang.RuntimeException: java.lang.NoSuchFieldException: loadedCoremods
    at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:552) ~[DepLoader$DepLoadInst.class:?]
    at codechicken.core.launch.DepLoader$DepLoadInst.activateDeps(DepLoader.java:502) ~[DepLoader$DepLoadInst.class:?]
    at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:496) ~[DepLoader$DepLoadInst.class:?]
    at codechicken.core.launch.DepLoader.load(DepLoader.java:684) ~[DepLoader.class:?]
    at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47) ~[CodeChickenCore-1.8-1.0.5.36-universal.jar:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_91]
    at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) [forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) [forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:127) [%5bGame%20Launcher%5dHello!%20Minecraft%20Launcher(HMCL).exe:?]
Caused by: java.lang.NoSuchFieldException: loadedCoremods
    at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_91]
    at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:539) ~[DepLoader$DepLoadInst.class:?]
    ... 23 more
[19:27:09] [main/ERROR] [LaunchWrapper]: Unable to launch

java.lang.RuntimeException: java.lang.NoSuchFieldException: loadedCoremods
    at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:552) ~[DepLoader$DepLoadInst.class:?]
    at codechicken.core.launch.DepLoader$DepLoadInst.activateDeps(DepLoader.java:502) ~[DepLoader$DepLoadInst.class:?]
    at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:496) ~[DepLoader$DepLoadInst.class:?]
    at codechicken.core.launch.DepLoader.load(DepLoader.java:684) ~[DepLoader.class:?]
    at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47) ~[CodeChickenCore-1.8-1.0.5.36-universal.jar:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_91]
    at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) ~[forge-1.8.9-11.15.1.1764.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:127) [%5bGame%20Launcher%5dHello!%20Minecraft%20Launcher(HMCL).exe:?]
Caused by: java.lang.NoSuchFieldException: loadedCoremods
    at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_91]
    at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:539) ~[DepLoader$DepLoadInst.class:?]
    ... 23 more
[19:27:11] [main/INFO] [STDERR]: [org.jackhuang.hellominecraft.launcher.Launcher:main:133]: Minecraft崩溃了！请认真阅读建议。

[19:27:11] [main/INFO] [STDERR]: [org.jackhuang.hellominecraft.launcher.Launcher:main:134]: 可能是Mod或其他问题。

[19:27:11] [main/INFO] [STDERR]: [org.jackhuang.hellominecraft.launcher.Launcher:main:135]: java.lang.reflect.InvocationTargetException

    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

    at java.lang.reflect.Method.invoke(Unknown Source)

    at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:127)

Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException

    at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)

    at java.lang.SecurityManager.checkExit(Unknown Source)

    at java.lang.Runtime.exit(Unknown Source)

    at java.lang.System.exit(Unknown Source)

    at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)

    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

    ... 5 more


 18, 2016 7:27:12  org.jackhuang.hellominecraft.launcher.Launcher main

*** Game Exited ***

Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[19:27:12] [Thread-9/ERROR] The game exited abnormally, exit code: 1

**Comment by covers1624** [comment]
1.8.9 is old, use 1.10!
