### ISSUE TITLE
loading crash during initialization 

### ISSUE THREAD

**Issue by leeharrill** [TheCBProject/NotEnoughItems#148]
here is the crash report 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)

**Comment by covers1624** [comment]
Gonna need the full crash report.

**Comment by jredfox** [comment]
not good enough go to %appdata%/.minecraft find crash reports organize by date modified and look for the top one then use pastebin and post it

**Comment by 330377782** [comment]
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/3/18 3:25 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.block.model.ModelBakery.field_177610_k from class codechicken.lib.model.loader.blockstate.CCBlockStateLoader
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.onTextureStitchPre(CCBlockStateLoader.java:126)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_121_CCBlockStateLoader_onTextureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:172)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.onTextureStitchPre(CCBlockStateLoader.java:126)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_121_CCBlockStateLoader_onTextureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:172)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 145750016 bytes (138 MB) / 382730240 bytes (365 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version       | Source                                        | Signature                                |
	|:----- |:--------------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2        | minecraft.jar                                 | None                                     |
	| UCH   | mcp                   | 9.42          | minecraft.jar                                 | None                                     |
	| UCH   | FML                   | 8.0.99.99     | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.2.2611  | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | backpacks16840        | 3.4.3         | backpacks+1.12.2+-+3.4.3.zip                  | None                                     |
	| UCH   | baubles               | 1.5.2         | Baubles-1.12-1.5.2.zip                        | None                                     |
	| UCH   | botania               | r1.10-353     | Botania+r1.10-353.jar                         | None                                     |
	| UCH   | codechickenlib        | 3.1.5.331     | CodeChickenLib-1.12.2-3.1.5.331-universal.zip | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cyclopscore           | 0.11.4        | CyclopsCore-1.12.2-0.11.4.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | colossalchests        | 1.6.9         | ColossalChests-1.12.2-1.6.9.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | jei                   | 4.8.5.159     | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UCH   | journeymap            | 1.12.2-5.5.2  | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCH   | lucky                 | 7.5.0         | LuckyBlock_1-12_v7-5-0.zip                    | None                                     |
	| UCH   | mantle                | 1.12-1.3.1.21 | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCH   | nei                   | 2.4.1         | NotEnoughItems-1.12.2-2.4.1.233-universal.zip | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | flammpfeil.slashblade | mc1.12-r10    | SlashBlade-mc1.12-r10.jar                     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 1060/PCIe/SSE2'
	Launched Version: HMCL 2.7.9.55
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.77, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by covers1624** [comment]
What ever WebBrowser you are using, has downloaded CCL with a .zip extension instead of .jar. Re-Download your mods using a propper web browser, like Chrome or Firefox.
