### ISSUE TITLE
hi hello this is what i get when i try and run this mod with the "needed items it requires"

### ISSUE THREAD

**Issue by KingFishy492** [TheCBProject/NotEnoughItems#185]
I have no idea why this happens (these are a downgraded version fro them being 100% uptodate as we thought that was the issue but it is still having the same issues no matter what versions they are 

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!
 
Time: 10/7/18 9:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail
 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
    at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
    at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
    at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:249)
    at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:54)
    at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- System Details --
Details:
    Minecraft Version: 1.12.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_181, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 180707704 bytes (172 MB) / 389283840 bytes (371 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.42 Powered by Forge 14.23.5.2768 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 
    | State | ID             | Version      | Source                                    | Signature                                |
    |:----- |:-------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
    | UCH   | minecraft      | 1.12.2       | minecraft.jar                             | None                                     |
    | UCH   | mcp            | 9.42         | minecraft.jar                             | None                                     |
    | UCH   | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
    | UCH   | forge          | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
    | UCEE  | codechickenlib | 3.1.5.331    | CodeChickenLib-1.12.2-3.1.5.331-deobf.jar | None                                     |
    | UC    | jei            | 4.8.6.162    | jei_1.12.2-4.8.6.162.jar                  | None                                     |
    | UC    | nei            | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.233-deobf.jar | None                                     |
 
    Loaded coremods (and transformers):
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 411.63' Renderer: 'GeForce GTX 965M/PCIe/SSE2'

**Comment by covers1624** [comment]
You have the -deobf jar's installed, these are for mod developers. Install -universal.

**Comment by KingFishy492** [comment]
universal didnt work either

**Comment by KingFishy492** [comment]
https://pastebin.com/ZeDMEsKS

**Comment by covers1624** [comment]
That crash is from JEI, nothing to do with me.

**Comment by KingFishy492** [comment]
eh but i posted to them and they said it was something to do with NEI https://github.com/mezz/JustEnoughItems/issues/1378

**Comment by Walkman100** [comment]
in your log on pastebin, note all the `at mezz.jei.*` messages, and the `UCHIJEE` (E is for error) next to `jei` in the mod state table, this is a JEI issue - it likely tries to use something that NEI changes, so it won't work with both. Not sure why you'd want both though...
