### ISSUE TITLE
Crash on Startup. Forge .2768, NEI .240, JEI .269. Pls Help.

### ISSUE THREAD

**Issue by Reznov981** [TheCBProject/NotEnoughItems#209]
Hey, I have that typical:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)

Full report below, please assist!

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 4/23/19 4:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setBoolean(Ljava/lang/String;Z)V
	at codechicken.nei.util.ItemStackMap.<clinit>(ItemStackMap.java:239)
	at codechicken.nei.NEIClientConfig.<clinit>(NEIClientConfig.java:53)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:68)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 483104384 bytes (460 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID             | Version      | Source                                    | Signature                                |
	|:------- |:-------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft      | 1.12.2       | minecraft.jar                             | None                                     |
	| UCHIJA  | mcp            | 9.42         | minecraft.jar                             | None                                     |
	| UCHIJA  | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge          | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | codechickenlib | 3.2.2.353    | CodeChickenLib-1.12.2.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | customnpcs     | 1.12         | CustomNPCs_1.12.2(30Jan19).jar            | None                                     |
	| UCHIJA  | jei            | 4.15.0.269   | jei_1.12.2-4.15.0.269.jar                 | None                                     |
	| UCHIJEE | nei            | 2.4.2        | NotEnoughItems-1.12.2-2.4.2.240-deobf.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-2.8.38' Renderer: 'AMD Radeon Pro 555 OpenGL Engine'

**Comment by covers1624** [comment]
You are running the deobfuscated version of nei, for mod developers, please run the `-universal` jar.

**Comment by Reznov981** [comment]
> You are running the deobfuscated version of nei, for mod developers, please run the `-universal` jar.

Ohhh I thought that was just a different download source option. Thanks!
