### ISSUE TITLE
1.10.2 crash: NoClassDefFoundError: bxl

### ISSUE THREAD

**Issue by joserobjr** [TheCBProject/NotEnoughItems#22]
@Chicken-Bones  It was mentioned in the older repository:
https://github.com/Chicken-Bones/NotEnoughItems/issues/354
https://github.com/Chicken-Bones/NotEnoughItems/issues/350

Minecraft just crashes with:
```java
java.lang.NoClassDefFoundError: bxl
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Using only:

- NotEnoughItems-1.10.2-2.1.1.147-universal
- CodeChickenCore-1.10.2-2.1.8.79-universal
- CodeChickenLib-1.10.2-2.2.3.78-universal
- Forge 1.10.2-12.18.1.2076 (also tested with 1.10.2-12.18.1.2011)

Full crash report: http://pastebin.com/6MM03SVz

**Comment by gigabit101** [comment]
This seems to happen if a mod gives a warning screen eg:needs more up to date forge version

**Comment by bjartskular** [comment]
I am also getting this same issue. I am only using the following:

- NotEnoughItems-1.10.2-2.1.1.147-universal
- CodeChickenCore-1.10.2-2.1.8.79-universal
- CodeChickenLib-1.10.2-2.2.3.80-universal
- Forge 1.10.2-12.18.1.2092

**Comment by covers1624** [comment]
Install JEI.
