### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jus74Dr3aM** [TheCBProject/NotEnoughItems#220]
<snip>
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:60)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:70)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:63)
</snip>

Somebody tell me to post it there soo

**Comment by raketexyz** [comment]
Update NEI, this was fixed ages ago. Download from here: [Chickenbones Downloadpage](http://chickenbones.net/Pages/links.html)
