### ISSUE TITLE
ANONYMOUS ARREST OF MINECRAFT DUE TO A MOD.

### ISSUE THREAD

**Issue by ArsenioLupin007** [TheCBProject/NotEnoughItems#225]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)

VIEW STOP REPORT:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/2/20 8:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:60)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:70)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 521080304 bytes (496 MB) / 4127195136 bytes (3936 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_F5 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version               | Source                                             | Signature                                |
	|:------ |:------------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                 | 9.42                  | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                 | 8.0.99.99             | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838          | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                       | minecraft.jar                                      | None                                     |
	| LCHIJA | cfm                 | 6.3.0                 | cfm-6.3.0-mc1.12.2.jar                             | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353             | CodeChickenLib-1.12.2.jar                          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | thedalekmod         | (Update 52.4.0)       | Dalek Mod - Update 52.4.jar                        | None                                     |
	| LCHIJA | ptrmodellib         | 1.0.4                 | PTRLib-1.12.2.jar                                  | None                                     |
	| LCHIJA | props               | 2.6.3                 | DecoCraft-Mod-1.12.2.jar                           | None                                     |
	| LCHIJA | ic2                 | 2.8.186-ex112         | Industrial-Craft-2-Mod-Experimental-1.12.2 (1).jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | galacticraftcore    | 4.0.2.210             | GalacticraftCore-1.12.2-4.0.2.210.jar              | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.210             | Galacticraft-Planets-1.12.2-4.0.2.210.jar          | None                                     |
	| LCHIJA | mjrlegendslib       | 1.12.2-1.1.7          | MJRLegendsLib-1.12.2.jar                           | None                                     |
	| LCHIJA | extraplanets        | 1.12.2-0.4.7          | ExtraPlanets-1.12.2.jar                            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | jei                 | 4.15.0.292            | jei_1.12.2-4.15.0.292.jar                          | None                                     |
	| LCHIJA | malisiscore         | 1.12.2-6.5.1-SNAPSHOT | MalisisCore-1.12.2.jar                             | None                                     |
	| LCHIJA | malisisdoors        | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| LCHIJA | mw                  | 1.11.7.7              | mw-1.11.7.7_mc1.12.2.jar                           | None                                     |
	| LCHIJE | nei                 | 2.4.1                 | Not-Enough-Items-1.12.2-Recommended (1).jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ  | redstoneflux        | 2.1.0                 | RedstoneFlux-1.12.2.jar                            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ  | scp                 | 2.1.1                 | SCP+Lockdown-1.12.2-2.1.1-beta.jar                 | None                                     |
	| LCHIJ  | securitycraft       | v1.8.9                | SecurityCraft-1.12.2.jar                           | None                                     |
	| LCHIJ  | thutcore            | 5.19.8                | ThutCore-1.12.2 (1).jar                            | None                                     |
	| LCHIJ  | thutcore_compat     | 1.0                   | ThutCore-1.12.2 (1).jar                            | None                                     |
	| LCHIJ  | thuttech            | 6.1.6                 | Thutmoses-Elevators-Mod-1.12.2.jar                 | None                                     |
	| LCHIJ  | car                 | 1.2.12                | Ultimate-Car-Mod-1.12.2.jar                        | None                                     |
	| LCHIJ  | xlfoodmod           | 1.12.2-1.9.2          | XL-Food-Mod-1.12.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.41' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.41
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by covers1624** [comment]
You are using an old version of NEI. Your jar name appears to be in the format that many repost sites use. Please ensure you only download your mods from either the official website of the mod, or from CurseForge. Here is NEI's curse page. http://minecraft.curseforge.com/projects/not-enough-items-1-8

**Comment by ArsenioLupin007** [comment]
Thank you so much for your help! Resolved
