### ISSUE TITLE
crash 1.10.2

### ISSUE THREAD

**Issue by Chunkimunki** [TheCBProject/NotEnoughItems#27]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.150-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 12/10/16 05:43
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModsMissing
	Mouse location: Scaled: (153, 18). Absolute: (307, 443)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1000891064 bytes (954 MB) / 1332215808 bytes (1270 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099-universal.jar) 
	U	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099-universal.jar) 
	U	CodeChickenCore{2.3.2.82} [CodeChicken Core] (minecraft.jar) 
	U	NotEnoughItems{2.1.2.150} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.150-universal.jar) 
	U	ChickenChunks{2.1.5.40} [ChickenChunks] (ChickenChunks-1.10.2-2.1.5.40-universal.jar) 
	U	EnderStorage{2.1.5.80} [EnderStorage] (EnderStorage-1.10.2-2.1.5.80-universal.jar) 
	Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.150-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)
  
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 6670'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6670 GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: conquest_reforged_RP (1).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by kaimokene** [comment]
You have to have Just enough items installed!

**Comment by Chunkimunki** [comment]
Ah of course - sorry I just assumed it was the NEI of old. Perhaps adding JEI as a dependancy might reduce stupid reports like mine

**Comment by covers1624** [comment]
It is marked as a dep, just Nei breaks missing mods screen.
