### ISSUE TITLE
NEI wont launch?!?!?

### ISSUE THREAD

**Issue by Smadger1** [TheCBProject/NotEnoughItems#29]
I have installed it with curse on 1.10.2 and when i launch it just with nei it crashes. here is the crash log.

2016-10-12 17:51:10,940 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-10-12 17:51:10,941 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[17:51:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:51:11] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:51:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:51:11] [main/INFO] [FML]: Forge Mod Loader version 12.18.1.2095 for Minecraft 1.10.2 loading
[17:51:11] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\Smadger\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
2016-10-12 17:51:11,180 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-10-12 17:51:11,200 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-10-12 17:51:11,204 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[17:51:11] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:51:11] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:51:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:51:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:51:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:51:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:51:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:51:13] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:51:13] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:51:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:51:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:51:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Exception in thread "main" [17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: codechicken/core/launch/CodeChickenCorePlugin
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at codechicken.nei.asm.NEICorePlugin.getASMTransformerClass(NEICorePlugin.java:17)
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:128)
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: codechicken.core.launch.CodeChickenCorePlugin
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:51:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    ... 4 more
[17:51:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[17:51:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[17:51:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     ... 6 more

**Comment by covers1624** [comment]
I know the issue, use the latest off cb's site.

**Comment by bestbug456** [comment]
@covers1624 I've the same problem too, can you explain what site is "cb"? Thanks in advice

**Comment by covers1624** [comment]
http://chickenbones.net/Pages/links.html

**Comment by gp009** [comment]
i have forge 1.10.2 and I have tried these from cb's site already and they crash with same result.  is there anything im missing?

**Comment by covers1624** [comment]
Update to latest
