### ISSUE TITLE
Crash when CCC/CCL is missing

### ISSUE THREAD

**Issue by mezz** [TheCBProject/NotEnoughItems#30]
With CCC and CCL missing I get this in the log and the game crashes:

```
Exception in thread "main" [23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ModularASMTransformer$ClassNodeTransformer
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Class.getDeclaredConstructors0(Native Method)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Class.getConstructor0(Class.java:3067)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Class.newInstance(Class.java:408)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:237)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at $wrapper.codechicken.nei.asm.NEITransformer.<init>(Unknown Source)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Class.newInstance(Class.java:438)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:131)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ModularASMTransformer$ClassNodeTransformer
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[23:35:52] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    ... 15 more
[23:35:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[23:35:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[23:35:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     ... 17 more
```

It should show the missing mods screen instead, now that #23 is fixed.

**Comment by covers1624** [comment]
This is now fixed. http://ss.podgeweb.com/35piikj.png \o/

**Comment by mezz** [comment]
Nice
