### ISSUE TITLE
potion recipe helper crash

### ISSUE THREAD

**Issue by LimeTheOn** [TheCBProject/NotEnoughItems#7]
This was unexpected...so its all good in sp and server runs just fine but when i join it crashes client. Help me out here, I got a server to run :D

```
Description: Unexpected error

java.lang.ClassCastException: crazypants.enderzoo.potion.Potions$ItemPredicateInstance cannot be cast to net.minecraft.potion.PotionHelper$ItemPredicateInstance
	at codechicken.nei.recipe.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:57)
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:101)
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:271)
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:212)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_599_ClientHandler_tickEvent_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:332)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.nei.recipe.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:57)
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:101)
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:271)
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:212)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_599_ClientHandler_tickEvent_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:332)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LimeOn'/270, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (233,67,210), Chunk: (at 9,4,2 in 14,13; contains blocks 224,0,208 to 239,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['LimeOn'/270, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by covers1624** [comment]
Wot.. ok ill whip something up

**Comment by LimeTheOn** [comment]
Cheers mate! <3

**Comment by covers1624** [comment]
Ok, build 133 on here http://chickenbones.net/Pages/links.html

**Comment by LimeTheOn** [comment]
testing, will get back to you in 5 min

**Comment by LimeTheOn** [comment]
nevermind 5 mins, it works! Huge thanks! So one question because i know that now we can put JEI on server-side too if we choose to but is it the same with NEI?

**Comment by covers1624** [comment]
Use JEI as well, ive been telling mod devs to not implement NEI as JEI is better, nei will load JEI stuff soon.

**Comment by LimeTheOn** [comment]
im using both atm im just asking if there's a point in adding NEI server-side too :) like... is there a feature or will there be a feature that encourages me to add it server-side? ->"nei will load JEI stuff soon." is that what you mean here?

**Comment by covers1624** [comment]
ohhh, you will be able to spawn items in creative without op, and some other little things ive probably forgotten :P

**Comment by LimeTheOn** [comment]
ahhhhhw ok, cheaty mod is cheaty :D as long as the players are not able to get creative without op on the server im fine with that :D

**Comment by LimeTheOn** [comment]
lol curse actually rejecting our update since your version is not official yet... you were nice enough to hotfix it for us and then...not gonna call them things but thats not nice on their end :D

**Comment by covers1624** [comment]
Interesting, Curse, LimeTheOn has my permission to ship the hotfixed version of NEI.

**Comment by covers1624** [comment]
Actually, ill just push an update on curse

**Comment by LimeTheOn** [comment]
Thank you! :D

**Comment by majix560** [comment]
I don't think it's fixed yet.
https://github.com/TheCBProject/NotEnoughItems/issues/8
